### ISSUE TITLE
Linking with `cc` fails with "undefined reference to `cblas_sgemm'" when features=["blas"]

### ISSUE THREAD

**Issue by wehlutyk** [bluss/rust-ndarray#251] opened 2016-12-19 10:06 UTC
I just started using ndarray (which I like a lot), and I'm hitting a weird bug when compiling with the "blas" feature activated. I might be missing something.

### Steps to reproduce

With Rust stable (1.13) on Archlinux. First `cargo new --bin testproject`, then set `Cargo.toml` to:

```toml
[package]
name = "testproject"
version = "0.1.0"
authors = ["John Doe <john@example.com>"]

[dependencies.ndarray]
version = "0.7.1"
features = ["blas"]
```

And `src/main.rs` to:

```rust
extern crate ndarray;

use ndarray::prelude::*;

fn main() {
    let line = arr2(&[[1, 2, 3]]);
    let column = arr2(&[[1], [2], [3]]);
    let result = column.dot(&line);
    println!("result = \n{:?}", &result);
}
```

Then `cargo build`.

### Expected behaviour

Should compile normally.

### Actual behaviour

Linking fails with the following final error:
```
note: /home/sl/Code/ML/appstat/testproject/target/debug/testproject.0.o: In function `ndarray::linalg::impl_linalg::mat_mul_impl<i32>':
/home/sl/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.7.1/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_sgemm'
/home/sl/.cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.7.1/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_dgemm'
collect2: error: ld returned 1 exit status
```

I ducked and googled around but couldn't find anything similar to this (other than xianyi/OpenBLAS#222). I have Archlinux's `blas 3.6.1-2`, `cblas 3.6.1-2`, and `lapack 3.6.1-2` installed and up to date. I tried installing Archlinux's OpenBLAS, which didn't change anything, and the issue disappears if I comment out the `features = ["blas"]` line in `Cargo.toml`.

Am I missing something obvious, do you think it's a problem with my setup, or is this a real bug? (maybe in `blas_sys`?)

### More logs

`rustup show`: http://pastebin.com/TPNEYs2e

`cargo clean` then `cargo build --verbose`: http://pastebin.com/WbW9MceC

```bash
$ uname -a
Linux iona 4.8.12-3-ARCH #1 SMP PREEMPT Thu Dec 8 16:10:23 CET 2016 x86_64 GNU/Linux
```

**Comment by bluss** [comment] 2016-12-19 10:33
I'm sorry, the expectation is wrong. "blas" activates using BLAS, but the user must pick a blas backend.

Picking backends correctly is hard to handle for library authors, I don't know the best way. We're just a library, and will not pick a default for you.

**Comment by bluss** [comment] 2016-12-19 10:38
That might seem annoying, but we need to figure out the best way for this. Our non-default seems to be the only flexible way when using cargo's crate feature system.

consider

- Multiple cargo crates want to use blas. How to pick the one backend that all of them use?
- How to plug in a backend that's not on crates.io? (Something self compiled).

**Comment by wehlutyk** [comment] 2016-12-19 10:40
Thanks for the quick answer, my bad!
Can you tell me how I should go about that? Can it be done through an environment variable?

**Comment by wehlutyk** [comment] 2016-12-19 10:47
I mean I see your point, but I have no idea as to how to inform the build process which BLAS backend I'd like to use.

**Comment by bluss** [comment] 2016-12-19 10:47
Adding an impl from crates.io works:

```
[dependencies]
netlib-src = "0.6" 
```


There are various ones, they need to be compiled by default (Which is annoying, using system libraries is faster).

I'd depend on netlib-src or; on openblas-src with feature system (should mean no compiling)

```
openblas-src = { version = "0.5", features = ["system"] }
```

blas-sys uses openblas as default. Ndarray depends on blas-sys without any defaults, exactly because this limits the user.

https://crates.io/crates/blas-sys

Anyway.. we need some ecosystem wide collaboration on the best way to solve it.

**Comment by wehlutyk** [comment] 2016-12-19 11:01
Right, I see the "library defaults" problem. Thanks for your help again. Now adding `netlib-src = "0.6" ` still gives me the same error. (And the same with `openblas-src`, feature system or not.) Anything else I could be missing?

**Comment by bluss** [comment] 2016-12-19 11:30
Hm ok, I can reproduce that. I thought I had checked it worked with netlib, but apparently not. I don't like this mess. Personally I just use this to circumvent it:

build.rs
```rust
//! This build script emits the openblas linking directive if requested
fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rustc-link-lib={}=openblas", "dylib");
}
```

I can recall depending on openblas-src with "system" to be equivalent, but it doesn't seem to work?

Now I certainly have a bug on my hands that needs fixing.

**Comment by wehlutyk** [comment] 2016-12-19 11:45
I just reinstalled openblas-lapack (from Arch AUR) and tried again with `openblas-src = { version = "0.5.2" , features = ["system"] }`, and it does fail with the same error. No idea what's going on.

The build.rs script works though!

**Comment by bluss** [comment] 2016-12-19 12:20
Ok, it's messy. openblas is linked to the openblas_src crate like it requests, so the main.rs file must do "extern crate openblas_src" to have *it* link to it transitively. It makes sense, but now to take a step back and find out how to solve this.

I don't believe in threading the backend alternatives through all libraries (crates like ndarray). One of the libraries is going to get it wrong, and it's going to be messy to ensure that all the libraries have the same backend.

**Comment by SuperFluffy** [comment] 2017-03-18 21:06
I was converting `scaled_add` to use `axpy` and ran into the same problem: how do you run tests and benchmarks against blas?

In fact, simply doing `cargo test --features blas` already causes the error:

```
% cargo test --features blas scale
   Compiling ndarray v0.8.0 (file:///home/janis/github/ndarray2)
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/janis/github/ndarray2/target/debug/deps/complex-f1f3ce09ae310f0a.0.o" "-o" "/home/janis/github/ndarray2/target/debug/deps/complex-f1f3ce09ae310f0a" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/janis/github/ndarray2/target/debug/deps" "-L" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-6c35a477e7bec8d3.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-a80f7c589731de53.rlib" "/home/janis/github/ndarray2/target/debug/deps/libndarray-309b293a54cbf602.rlib" "/home/janis/github/ndarray2/target/debug/deps/libnum_complex-63e391e2b3ca61b7.rlib" "/home/janis/github/ndarray2/target/debug/deps/libnum_traits-69f4129d46397118.rlib" "/home/janis/github/ndarray2/target/debug/deps/libitertools-2c1f6d23e119647e.rlib" "/home/janis/github/ndarray2/target/debug/deps/libblas_sys-ed936d315bdab911.rlib" "/home/janis/github/ndarray2/target/debug/deps/liblibc-5dc7b85e748840b4.rlib" "/home/janis/github/ndarray2/target/debug/deps/libmatrixmultiply-f1139eb0050ad26b.rlib" "/home/janis/github/ndarray2/target/debug/deps/librawpointer-dc9eeb50dff13477.rlib" "/home/janis/github/ndarray2/target/debug/deps/libeither-7d89001e12282025.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-fa872424129019f5.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-f4594d3e53dcb114.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a0157c0ca919c364.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-488b4ab4bd53a138.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1efbcfd8938372b6.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-532a3dbf317eff86.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ca07b617414dd0fa.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-492d8ea7fa3384ff.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-88c194c15fdb6521.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-cfbd6648f7db2ee5.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-687e6a964d22cbb4.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-987729be881d4d32.rlib" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /home/janis/github/ndarray2/target/debug/deps/complex-f1f3ce09ae310f0a.0.o: In function `ndarray::linalg::impl_linalg::mat_mul_impl<num_complex::Complex<f64>>':
          /home/janis/github/ndarray2/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_sgemm'
          /home/janis/github/ndarray2/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_dgemm'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `ndarray`.
Build failed, waiting for other jobs to finish...
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/janis/github/ndarray2/target/debug/examples/linalg-a725800dc6878332.0.o" "-o" "/home/janis/github/ndarray2/target/debug/examples/linalg-a725800dc6878332" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/home/janis/github/ndarray2/target/debug/deps" "-L" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/home/janis/github/ndarray2/target/debug/deps/libndarray-309b293a54cbf602.rlib" "/home/janis/github/ndarray2/target/debug/deps/libmatrixmultiply-f1139eb0050ad26b.rlib" "/home/janis/github/ndarray2/target/debug/deps/libblas_sys-ed936d315bdab911.rlib" "/home/janis/github/ndarray2/target/debug/deps/librawpointer-dc9eeb50dff13477.rlib" "/home/janis/github/ndarray2/target/debug/deps/liblibc-5dc7b85e748840b4.rlib" "/home/janis/github/ndarray2/target/debug/deps/libitertools-2c1f6d23e119647e.rlib" "/home/janis/github/ndarray2/target/debug/deps/libeither-7d89001e12282025.rlib" "/home/janis/github/ndarray2/target/debug/deps/libnum_complex-63e391e2b3ca61b7.rlib" "/home/janis/github/ndarray2/target/debug/deps/libnum_traits-69f4129d46397118.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-f4594d3e53dcb114.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a0157c0ca919c364.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-488b4ab4bd53a138.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-1efbcfd8938372b6.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-532a3dbf317eff86.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-ca07b617414dd0fa.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-492d8ea7fa3384ff.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-88c194c15fdb6521.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-cfbd6648f7db2ee5.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-687e6a964d22cbb4.rlib" "/home/janis/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-987729be881d4d32.rlib" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /home/janis/github/ndarray2/target/debug/examples/linalg-a725800dc6878332.0.o: In function `ndarray::linalg::impl_linalg::mat_mul_impl<f64>':
          /home/janis/github/ndarray2/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_sgemm'
          /home/janis/github/ndarray2/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_dgemm'
          /home/janis/github/ndarray2/target/debug/examples/linalg-a725800dc6878332.0.o: In function `ndarray::linalg::impl_linalg::mat_mul_impl<f32>':
          /home/janis/github/ndarray2/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_sgemm'
          /home/janis/github/ndarray2/src/linalg/impl_linalg.rs:371: undefined reference to `cblas_dgemm'
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `ndarray`.
Build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bluss** [comment] 2017-03-18 21:27
black backend selection is unresolved. The blas feature for testing uses system openblas (It works in travis)

**Comment by bluss** [comment] 2017-03-18 21:29
Testing uses `cargo test --features test` in fact to use system openblas as in travis

**Comment by SuperFluffy** [comment] 2017-03-18 22:44
How is the dependency chain working though? This is the definition in Cargo.toml:

```
[dependencies]
# Use via the `blas` crate feature!
blas-sys = { version = "0.6.5", optional = true, default-features = false }

[features]
blas = ["blas-sys"]

# These features are used for testing
blas-openblas-sys = ["blas"]
test = ["blas-openblas-sys"]
```

So, `test` expands to `blas-openblas-sys`, which expands to `blas`, which finally pulls in `blas-sys`, which is an actual crate in its own right. I feel like I am misunderstanding how this is supposed to be working and at which moment openblas gets pulled in.

It just rebuild/updated my local openblas and it looks like things work now. :-)

**Comment by bluss** [comment] 2017-03-19 00:33
blas-openblas-sys is used in build.rs. It's not documented so it's for testing. Users should select backend using blas-sys

**Comment by bluss** [comment] 2017-04-08 23:08
## Intended Usage

`ndarray` is just a library and the end user application must be free to select BLAS provider as they please. That's the root of the design right now, which depends on blas-sys but asks it to have no default.

Intended usage is like below, the application depends on ndarray and on blas-sys to select the provider.

```toml
[package]
name = "testblas"
version = "0.1.0"
authors = ["bluss"]

[dependencies]
ndarray = { version = "0.8", features = ["blas"] }
blas-sys = { version = "*",  default-features=false, features=["netlib"] }
```

And this compiles and works fine.

In fact just a dependency on plain `blas-sys` works and then you get their default.

What I'm not happy about is the coupling here if we want to set more flags (netlib/openblas by dynamic linking to already installed library instead of compiling it) and so on!

**Comment by bluss** [comment] 2017-04-14 11:50
The intended working way of picking a blas provider is now documented in README, so I'm going to close this issue. As you can tell, the interface to all of this is far from optimal.

**Closed by bluss** 2017-04-14 11:50 UTC
